# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: umid12
      POSTGRES_USER: umid
      POSTGRES_DB: Multikart

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redisdb:
    image: redis
    ports:
      - 6379:6379