# Generated by Django 4.0.4 on 2022-07-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Email Adress')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone')),
                ('country', models.CharField(choices=[('Aze', 'Azerbaijan'), ('Tur', 'Turkey')], default='Aze', max_length=3, verbose_name='Counrty')),
                ('adress', models.CharField(max_length=50, verbose_name='Adress')),
                ('city', models.CharField(max_length=50, verbose_name='City/Town')),
                ('state', models.CharField(max_length=50, null=True, verbose_name='State/Counrty')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('create_an_account', models.BooleanField(default=False, verbose_name='Create an Account?')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Free Shipping')),
                ('local_pickup', models.BooleanField(default=False, verbose_name='Local Pickup')),
            ],
            options={
                'verbose_name': 'Checkout',
                'verbose_name_plural': 'Checkout',
            },
        ),
    ]
